languague: python
notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - DOCKER_IMAGE=csrg/generic_builder
        - PATH=/opt/conda/bin:$PATH

install:
  - sudo docker pull $DOCKER_IMAGE

script:
  - sudo docker run -e PATH=$PATH --rm -v `pwd`:/workspace $DOCKER_IMAGE /workspace/travis/build-wheels.sh

after_success:
  - pip install twine
  - (twine upload dist/* -u $USER -p $PASSWORD --skip-existing  || echo "Not last release")
